spring.application.name=igaming-source-caliente
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://igaming-source-caliente-db.igaming-source.svc.cluster.local:5432/igaming_caliente}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.validation-timeout=3000
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

app.aggregator.url=${APP_AGGREGATOR_URL:http://igaming-aggregator.igaming-dev.svc.cluster.local:8080}
app.caliente.api-url=${APP_CALIENTE_API_URL:https://sports.caliente.mx}
app.caliente.use-proxy=${APP_CALIENTE_USE_PROXY:true}
app.caliente.proxy-host=${APP_CALIENTE_PROXY_HOST:100.83.113.50}
app.caliente.proxy-port=${APP_CALIENTE_PROXY_PORT:3128}
app.caliente.poll-rate-ms=${APP_CALIENTE_POLL_RATE_MS:10000}
