FROM eclipse-temurin:21-jre-jammy

RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    curl \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Install Google Chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable \
    && rm -rf /var/lib/apt/lists/*

# Install Node.js to use Playwright CLI for deps
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

# Install Playwright System Dependencies for Chromium, Firefox, WebKit
RUN npm install -g playwright@1.43.0 \
    && npx playwright install-deps \
    && rm -rf /root/.npm

ENV PLAYWRIGHT_BROWSERS_PATH=/root/.cache/ms-playwright
