apiVersion: v1
kind: Service
metadata:
  name: igaming-sources-db
  namespace: igaming-dev
spec:
  selector:
    app: igaming-sources-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: igaming-sources-db
  namespace: igaming-dev
spec:
  serviceName: igaming-sources-db
  replicas: 1
  selector:
    matchLabels:
      app: igaming-sources-db
  template:
    metadata:
      labels:
        app: igaming-sources-db
    spec:
      nodeSelector:
        node-type: standard
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 2Gi
        args:
        - -c
        - max_connections=1000
        - -c
        - shared_buffers=512MB
        - -c
        - work_mem=16MB
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata
      volumes:
      - name: pgdata
        emptyDir: {}
