apiVersion: v1
kind: Namespace
metadata:
  name: service-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: service-proxy-backend
  namespace: service-proxy
spec:
  type: ExternalName
  externalName: service-proxy-backend.proxy.svc.cluster.local
