apiVersion: v1
kind: Secret
metadata:
  name: accounts-db-secret
  namespace: accounts
type: Opaque
stringData:
  db-user: "postgres"
  db-password: "changeme"
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-db
  namespace: accounts
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: accounts-db
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accounts-db-pvc
  namespace: accounts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: accounts-db
  namespace: accounts
spec:
  serviceName: accounts-db
  replicas: 1
  selector:
    matchLabels:
      app: accounts-db
  template:
    metadata:
      labels:
        app: accounts-db
    spec:
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        node-type: master
      containers:
      - name: accounts-db
        image: postgres:16
        env:
        - name: POSTGRES_DB
          value: "accounts"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: accounts-db-secret
              key: db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: accounts-db-secret
              key: db-password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: accounts-db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: accounts-db-data
        persistentVolumeClaim:
          claimName: accounts-db-pvc
