apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service
  namespace: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-service
  template:
    metadata:
      labels:
        app: accounts-service
    spec:
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        node-type: master
      containers:
      - name: accounts-service
        image: ghcr.io/datawikipro/accounts-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8091
        env:
        - name: DB_URL
          value: "jdbc:postgresql://accounts-db:5432/accounts"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: accounts-db-secret
              key: db-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: accounts-db-secret
              key: db-password
        - name: HOSTNAME
          value: "0.0.0.0"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8091
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8091
          initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  namespace: accounts
spec:
  selector:
    app: accounts-service
  ports:
  - protocol: TCP
    port: 8091
    targetPort: 8091
  type: ClusterIP
