schema: spec-driven
created: 2026-10-06
<<<<<<< HEAD
task_id: "8f4b939f-411a-46c0-9b70-741b26c028df"
title: "[SMM OFFLINE] Сервис публикации постов smm-bot-telegram недоступен"
=======
task_id: "8f4b939f-9269-4bcf-af18-c1f34bc2816d"
title: "#998: [SMM OFFLINE] Сервис публикации постов smm-bot-telegram недоступен"
>>>>>>> feature/plane-8f4b939f
