apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postiz-uploads-pvc
  namespace: postiz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
