schema: spec-driven
created: 2026-10-06
task_id: "03d2f732-81c8-4e40-84f5-2884ef255a17"
<<<<<<< HEAD
title: "#620: [HIGH LAG] Критическое отставание линии 1xBit (33.1 мин)"
=======
title: "[HIGH LAG] Критическое отставание линии 1xBit (33.1 мин)"
>>>>>>> feature/plane-03d2f732
