schema: spec-driven
created: 2026-10-06
task_id: "10eab33b-9e51-45cf-a48a-39ad9eb72e7d"
<<<<<<< HEAD
title: "[SUPER-ARB] Аномальная вилка 41.0% с участием BetM"
=======
title: "#425: [SUPER-ARB] Аномальная вилка 41.0% с участием BetM"
>>>>>>> feature/plane-06e51210
