spring.application.name=igaming-source-digitain
spring.profiles.active=${SPRING_PROFILES_ACTIVE:league-crawler}

server.port=${SERVER_PORT:3080}

app.vpn.enabled=true
app.bookmaker.region=${APP_BOOKMAKER_REGIONS:ru}
app.target.host=melbet.ru

# Proxy backend
app.proxy.backend.url=${APP_PROXY_BACKEND_URL:http://service-proxy-backend.service-proxy.svc.cluster.local}
app.aggregator.url=${APP_AGGREGATOR_URL:http://igaming-aggregator.igaming-dev.svc.cluster.local}

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/igaming_digitain}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka.kafka.svc.cluster.local:9092}

# Crawler Configuration
app.crawler.delay=${CRAWLER_DELAY:60000}
