server.port=3049
spring.application.name=igaming-source-xbet
app.bookmaker.name=1xbet
app.bookmaker.regions=INT,EU
app.aggregator.url=http://localhost:3000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# 1xBet / BetB2B Family Feed JSON API
app.xbet.live-url=https://1xbet.com/LiveFeed/Get1xMatchByLeague?sports=1
app.xbet.prematch-url=https://1xbet.com/LineFeed/Get1xMatchByLeague?sports=1

# Local Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DATABASE_HOST:localhost}:5432/igaming_xbet}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
