apiVersion: v1
kind: Service
metadata:
  name: igaming-source-1xbet-crawler
  namespace: igaming-dev
spec:
  selector:
    app: igaming-source-1xbet-crawler
  ports:
  - protocol: TCP
    port: 3049
    targetPort: 3049
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: igaming-source-1xbet-crawler
  namespace: igaming-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igaming-source-1xbet-crawler
  template:
    metadata:
      labels:
        app: igaming-source-1xbet-crawler
    spec:
      imagePullSecrets:
      - name: regcred
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - standard
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - spot
                - standard
      containers:
      - name: igaming-source-1xbet-crawler
        image: ghcr.io/datawikipro/igaming-source-betb2b:latest
        imagePullPolicy: Always
        env:
        - name: APP_BROWSER_STEALTH_PROFILE
          value: XVFB_HEADED
        - name: SPRING_APPLICATION_NAME
          value: igaming-source-1xbet
        - name: APP_TARGET_HOST
          value: 1xbet.com
        - name: SPRING_PROFILES_ACTIVE
          value: league-crawler
        - name: SERVER_PORT
          value: '3049'
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://igaming-source-1xbet-db:5432/igaming_xbet
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
        - name: APP_AGGREGATOR_URL
          value: http://igaming-aggregator
        - name: SPRING_DATA_REDIS_HOST
          value: localhost
        - name: APP_PERSISTENCE_USE_REDIS_FACTORS
          value: 'true'
        - name: APP_PROXY_BACKEND_URL
          value: http://service-proxy-backend.service-proxy.svc.cluster.local
        - name: APP_BOOKMAKER_NAME
          value: 1xbet
        - name: APP_BOOKMAKER_REGIONS
          value: INT,EU
        - name: APP_XBET_LIVE_URL
          value: https://1xbet.com/LiveFeed/Get1xMatchByLeague?sports=1
        - name: APP_XBET_PREMATCH_URL
          value: https://1xbet.com/LineFeed/Get1xMatchByLeague?sports=1
        - name: APP_XBET_PARTNER_ID
          value: '321'
        - name: JAVA_OPTS
          value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=50.0 -XX:+UseG1GC -XX:MaxGCPauseMillis=200
            -XX:+UseStringDeduplication -XshowSettings:vm
        ports:
        - containerPort: 3049
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: '1'
            memory: 1.5Gi
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: igaming-source-1xbet-loader
  namespace: igaming-dev
spec:
  selector:
    app: igaming-source-1xbet-loader
  ports:
  - protocol: TCP
    port: 3049
    targetPort: 3049
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: igaming-source-1xbet-loader
  namespace: igaming-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igaming-source-1xbet-loader
  template:
    metadata:
      labels:
        app: igaming-source-1xbet-loader
    spec:
      imagePullSecrets:
      - name: regcred
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - standard
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - spot
                - standard
      containers:
      - name: igaming-source-1xbet-loader
        image: ghcr.io/datawikipro/igaming-source-betb2b:latest
        imagePullPolicy: Always
        env:
        - name: SPRING_APPLICATION_NAME
          value: igaming-source-1xbet
        - name: APP_TARGET_HOST
          value: 1xbet.com
        - name: SPRING_PROFILES_ACTIVE
          value: match-loader
        - name: SERVER_PORT
          value: '3049'
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://igaming-source-1xbet-db:5432/igaming_xbet
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
        - name: APP_AGGREGATOR_URL
          value: http://igaming-aggregator
        - name: SPRING_DATA_REDIS_HOST
          value: localhost
        - name: APP_PERSISTENCE_USE_REDIS_FACTORS
          value: 'true'
        - name: APP_PROXY_BACKEND_URL
          value: http://service-proxy-backend.service-proxy.svc.cluster.local
        - name: APP_BOOKMAKER_NAME
          value: 1xbet
        - name: APP_BOOKMAKER_REGIONS
          value: INT,EU
        - name: APP_XBET_LIVE_URL
          value: https://1xbet.com/LiveFeed/Get1xMatchByLeague?sports=1
        - name: APP_XBET_PREMATCH_URL
          value: https://1xbet.com/LineFeed/Get1xMatchByLeague?sports=1
        - name: APP_XBET_PARTNER_ID
          value: '321'
        - name: JAVA_OPTS
          value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=50.0 -XX:+UseG1GC -XX:MaxGCPauseMillis=200
            -XX:+UseStringDeduplication -XshowSettings:vm
        ports:
        - containerPort: 3049
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: '1'
            memory: 1.5Gi
        livenessProbe:
          httpGet:
            path: /api/v1/monitoring/info
            port: 3049
          initialDelaySeconds:  240
          periodSeconds: 15
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/monitoring/info
            port: 3049
          initialDelaySeconds:  180
          periodSeconds: 10
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: igaming-source-1xbet-db
  namespace: igaming-dev
spec:
  selector:
    app: igaming-source-1xbet-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: igaming-source-1xbet-db
  namespace: igaming-dev
spec:
  serviceName: igaming-source-1xbet-db
  replicas: 1
  selector:
    matchLabels:
      app: igaming-source-1xbet-db
  template:
    metadata:
      labels:
        app: igaming-source-1xbet-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: igaming_xbet
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata
      volumes:
      - name: pgdata
        emptyDir: {}
