apiVersion: v1
kind: Service
metadata:
  name: igaming-source-betcity-crawler
  namespace: igaming-dev
spec:
  selector:
    app: igaming-source-betcity-crawler
  ports:
  - protocol: TCP
    port: 3041
    targetPort: 3041
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: igaming-source-betcity-crawler
  namespace: igaming-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igaming-source-betcity-crawler
  template:
    metadata:
      labels:
        app: igaming-source-betcity-crawler
    spec:
      imagePullSecrets:
      - name: regcred
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - standard
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - spot
                - standard
      containers:
      - name: igaming-source-betcity-crawler
        image: ghcr.io/datawikipro/igaming-source-betcity:latest
        imagePullPolicy: Always
        env:
        - name: APP_BROWSER_STEALTH_PROFILE
          value: HEADLESS_STEALTH
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: APP_ROLE
          value: league-crawler
        - name: SERVER_PORT
          value: '3041'
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://igaming-source-betcity-db:5432/igaming_betcity
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
        - name: SPRING_DATA_REDIS_HOST
          value: localhost
        - name: APP_PERSISTENCE_USE_REDIS_FACTORS
          value: 'true'
        - name: APP_PROXY_BACKEND_URL
          value: http://service-proxy-backend.service-proxy.svc.cluster.local
        - name: APP_AGGREGATOR_URL
          value: http://igaming-aggregator
        - name: APP_BOOKMAKER_NAME
          value: betcity
        - name: APP_BOOKMAKER_REGIONS
          value: RU
        - name: APP_TARGET_HOST
          value: ad.betcity.ru
        - name: APP_BETCITY_LIVE_URL
          value: https://ad.betcity.ru/d/on_air/bets?rev=8&add=dep_event&template=1
        - name: APP_BETCITY_PREMATCH_URL
          value: https://ad.betcity.ru/d/off/events?rev=6
        - name: APP_BETCITY_EVENT_URL_TEMPLATE
          value: https://betcity.ru/ru/line/bets?id=%s
        ports:
        - containerPort: 3041
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: '1'
            memory: 1.5Gi
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: igaming-source-betcity-loader
  namespace: igaming-dev
spec:
  selector:
    app: igaming-source-betcity-loader
  ports:
  - protocol: TCP
    port: 3041
    targetPort: 3041
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: igaming-source-betcity-loader
  namespace: igaming-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igaming-source-betcity-loader
  template:
    metadata:
      labels:
        app: igaming-source-betcity-loader
    spec:
      imagePullSecrets:
      - name: regcred
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - standard
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - spot
                - standard
      containers:
      - name: igaming-source-betcity-loader
        image: ghcr.io/datawikipro/igaming-source-betcity:latest
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: APP_ROLE
          value: match-loader
        - name: SERVER_PORT
          value: '3041'
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://igaming-source-betcity-db:5432/igaming_betcity
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
        - name: SPRING_DATA_REDIS_HOST
          value: localhost
        - name: APP_PERSISTENCE_USE_REDIS_FACTORS
          value: 'true'
        - name: APP_PROXY_BACKEND_URL
          value: http://service-proxy-backend.service-proxy.svc.cluster.local
        - name: APP_AGGREGATOR_URL
          value: http://igaming-aggregator
        - name: APP_BOOKMAKER_NAME
          value: betcity
        - name: APP_BOOKMAKER_REGIONS
          value: RU
        - name: APP_TARGET_HOST
          value: ad.betcity.ru
        - name: APP_BETCITY_LIVE_URL
          value: https://ad.betcity.ru/d/on_air/bets?rev=8&add=dep_event&template=1
        - name: APP_BETCITY_PREMATCH_URL
          value: https://ad.betcity.ru/d/off/events?rev=6
        - name: APP_BETCITY_EVENT_URL_TEMPLATE
          value: https://betcity.ru/ru/line/bets?id=%s
        ports:
        - containerPort: 3041
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: '1'
            memory: 1.5Gi
        livenessProbe:
          httpGet:
            path: /api/v1/monitoring/info
            port: 3041
          initialDelaySeconds:  240
          periodSeconds: 15
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/monitoring/info
            port: 3041
          initialDelaySeconds:  180
          periodSeconds: 10
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: igaming-source-betcity-db
  namespace: igaming-dev
spec:
  selector:
    app: igaming-source-betcity-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: igaming-source-betcity-db
  namespace: igaming-dev
spec:
  serviceName: igaming-source-betcity-db
  replicas: 1
  selector:
    matchLabels:
      app: igaming-source-betcity-db
  template:
    metadata:
      labels:
        app: igaming-source-betcity-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: igaming_betcity
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata
      volumes:
      - name: pgdata
        emptyDir: {}
