apiVersion: v1
kind: Service
metadata:
  name: igaming-aggregator
  namespace: igaming-source
spec:
  type: ExternalName
  externalName: igaming-aggregator.igaming-master.svc.cluster.local
  ports:
  - port: 80
    targetPort: 80

