apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: igaming-source
spec:
  type: ExternalName
  externalName: kafka.igaming-master.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: igaming-source
spec:
  type: ExternalName
  externalName: kafka.igaming-master.svc.cluster.local
