apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: igaming-source-leon-db
  namespace: igaming-dev
  labels:
    app: igaming-source-leon-db
spec:
  serviceName: igaming-source-leon-db
  replicas: 1
  selector:
    matchLabels:
      app: igaming-source-leon-db
  template:
    metadata:
      labels:
        app: igaming-source-leon-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: igaming_leon
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: igaming-source-leon-db
  namespace: igaming-dev
spec:
  type: ClusterIP
  selector:
    app: igaming-source-leon-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: igaming-source-leon-crawler
  namespace: igaming-dev
  labels:
    app: igaming-source-leon-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igaming-source-leon-crawler
  template:
    metadata:
      labels:
        app: igaming-source-leon-crawler
    spec:
      imagePullSecrets:
      - name: regcred
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - standard
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - spot
                - standard
      containers:
      - name: igaming-source-leon
        image: ghcr.io/datawikipro/igaming-source-leon:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3037
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev,league-crawler
        - name: DATABASE_HOST
          value: igaming-source-leon-db
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://igaming-source-leon-db:5432/igaming_leon
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
        - name: APP_AGGREGATOR_URL
          value: http://igaming-aggregator:80
        - name: SPRING_DATA_REDIS_HOST
          value: localhost
        - name: APP_PERSISTENCE_USE_REDIS_FACTORS
          value: 'true'

        - name: APP_PROXY_BACKEND_URL
          value: 'http://service-proxy-backend.service-proxy.svc.cluster.local'
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 1.5
            memory: 3.5Gi
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: igaming-source-leon-loader
  namespace: igaming-dev
  labels:
    app: igaming-source-leon-loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igaming-source-leon-loader
  template:
    metadata:
      labels:
        app: igaming-source-leon-loader
    spec:
      imagePullSecrets:
      - name: regcred
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - standard
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - spot
                - standard
      containers:
      - name: igaming-source-leon
        image: ghcr.io/datawikipro/igaming-source-leon:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3037
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev,match-loader
        - name: DATABASE_HOST
          value: igaming-source-leon-db
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://igaming-source-leon-db:5432/igaming_leon
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
        - name: APP_AGGREGATOR_URL
          value: http://igaming-aggregator:80
        - name: SPRING_DATA_REDIS_HOST
          value: localhost
        - name: APP_PERSISTENCE_USE_REDIS_FACTORS
          value: 'true'

        - name: APP_PROXY_BACKEND_URL
          value: 'http://service-proxy-backend.service-proxy.svc.cluster.local'
        resources:
          requests:
            cpu: 150m
            memory: 512Mi
          limits:
            cpu: 1.5
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /api/v1/monitoring/info
            port: 3037
          initialDelaySeconds:  240
          periodSeconds: 15
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/monitoring/info
            port: 3037
          initialDelaySeconds:  180
          periodSeconds: 10
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: igaming-source-leon
  namespace: igaming-dev
spec:
  type: ClusterIP
  selector:
    app: igaming-source-leon-loader
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3037

