apiVersion: v1
kind: Service
metadata:
  name: igaming-source-olimpbet-crawler
  namespace: igaming-dev
spec:
  selector:
    app: igaming-source-olimpbet-crawler
  ports:
  - protocol: TCP
    port: 3039
    targetPort: 3039
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: igaming-source-olimpbet-crawler
  namespace: igaming-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igaming-source-olimpbet-crawler
  template:
    metadata:
      labels:
        app: igaming-source-olimpbet-crawler
    spec:
      imagePullSecrets:
      - name: regcred
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - standard
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - spot
                - standard
      containers:
      - name: igaming-source-olimpbet-crawler
        image: ghcr.io/datawikipro/igaming-source-olimpbet:latest
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: APP_ROLE
          value: league-crawler
        - name: SERVER_PORT
          value: '3039'
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://igaming-source-olimpbet-db:5432/igaming_olimpbet
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
        - name: SPRING_DATA_REDIS_HOST
          value: localhost
        - name: APP_PERSISTENCE_USE_REDIS_FACTORS
          value: 'true'
        - name: APP_PROXY_BACKEND_URL
          value: http://service-proxy-backend.service-proxy.svc.cluster.local
        - name: APP_AGGREGATOR_URL
          value: http://igaming-aggregator
        - name: APP_BOOKMAKER_NAME
          value: olimpbet
        - name: APP_BOOKMAKER_REGIONS
          value: RU
        - name: APP_TARGET_HOST
          value: www.olimp.bet
        - name: APP_OLIMPBET_LIVE_URL
          value: https://www.olimp.bet/api/v4/0/live/popular/sports-with-competitions-with-events
        - name: APP_OLIMPBET_PREMATCH_URL
          value: https://www.olimp.bet/api/v4/0/line/top/sports-with-competitions-with-events
        ports:
        - containerPort: 3039
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: '1'
            memory: 1.5Gi
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: igaming-source-olimpbet-loader
  namespace: igaming-dev
spec:
  selector:
    app: igaming-source-olimpbet-loader
  ports:
  - protocol: TCP
    port: 3039
    targetPort: 3039
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: igaming-source-olimpbet-loader
  namespace: igaming-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: igaming-source-olimpbet-loader
  template:
    metadata:
      labels:
        app: igaming-source-olimpbet-loader
    spec:
      imagePullSecrets:
      - name: regcred
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - standard
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - spot
                - standard
      containers:
      - name: igaming-source-olimpbet-loader
        image: ghcr.io/datawikipro/igaming-source-olimpbet:latest
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: APP_ROLE
          value: match-loader
        - name: SERVER_PORT
          value: '3039'
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://igaming-source-olimpbet-db:5432/igaming_olimpbet
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
        - name: SPRING_DATA_REDIS_HOST
          value: localhost
        - name: APP_PERSISTENCE_USE_REDIS_FACTORS
          value: 'true'
        - name: APP_PROXY_BACKEND_URL
          value: http://service-proxy-backend.service-proxy.svc.cluster.local
        - name: APP_AGGREGATOR_URL
          value: http://igaming-aggregator
        - name: APP_BOOKMAKER_NAME
          value: olimpbet
        - name: APP_BOOKMAKER_REGIONS
          value: RU
        - name: APP_TARGET_HOST
          value: www.olimp.bet
        - name: APP_OLIMPBET_LIVE_URL
          value: https://www.olimp.bet/api/v4/0/live/popular/sports-with-competitions-with-events
        - name: APP_OLIMPBET_PREMATCH_URL
          value: https://www.olimp.bet/api/v4/0/line/top/sports-with-competitions-with-events
        ports:
        - containerPort: 3039
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: '1'
            memory: 1.5Gi
        livenessProbe:
          httpGet:
            path: /api/v1/monitoring/info
            port: 3039
          initialDelaySeconds:  240
          periodSeconds: 15
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/monitoring/info
            port: 3039
          initialDelaySeconds:  180
          periodSeconds: 10
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: igaming-source-olimpbet-db
  namespace: igaming-dev
spec:
  selector:
    app: igaming-source-olimpbet-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: igaming-source-olimpbet-db
  namespace: igaming-dev
spec:
  serviceName: igaming-source-olimpbet-db
  replicas: 1
  selector:
    matchLabels:
      app: igaming-source-olimpbet-db
  template:
    metadata:
      labels:
        app: igaming-source-olimpbet-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: igaming_olimpbet
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata
  volumeClaimTemplates:
  - metadata:
      name: pgdata
      namespace: igaming-dev
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
